### ISSUE TITLE
Example tests report

### ISSUE THREAD

**Issue by kororro** [ChrisDill/Raylib-cs-Examples#17]
Hi, thanks for these cs bindings.

Just downloaded these from git, and tested all tests:
* texture explosion crashes (but if starting from that test, it works)
* billboard test doesnt use alpha like in https://www.raylib.com/examples/web/models/loader.html?name=models_billboard
* pbr test, that helmet looks gray, material doesnt work?
* models_mesh_generation crashes when tested tests before that, but when starting from that, it works
* audio tests only first one works, others does not have audio (but works if only one test is tested)

I know that in a real game nobody shuts down and recreates window&audio tens of time, but because there is issues, I think it is that disposing/releasing (ie audio) isnt working (or used, havent checked the code).

So all tests works, but not directly.

**Comment by ChrisDill** [comment]
Audio examples now work as expected. Please open a new issue if you run into any further problems with the examples.
