### ISSUE TITLE
ImGuiDemo display issue on MacOS!

### ISSUE THREAD

**Issue by zhengying** [ChrisDill/Raylib-cs-Examples#19]
<img width="739" alt="Screen Shot 2022-10-30 at 9 42 00 AM" src="https://user-images.githubusercontent.com/1042545/198858904-247a0f74-bcd8-45f2-8da7-8dd4ba79a999.png">
macOS 11.6 .net core 6.0.

**Comment by differenceclouds** [comment]
You can either use an external non-hidpi monitor, or use a program like Quickres to switch to low-dpi. There's also this if you're using XCode (which of course you aren't if it's raylib-cs): https://www.reddit.com/r/raylib/comments/o3k27c/macos_fix_high_dpi_blurry_window/
So you would set
<key>NSHighResolutionCapable</key>
<false/>
I'm unsure of the equivalent key in Visual Studio, or if there is one...
