### ISSUE TITLE
StorageValues example doesn't work - No entry point SaveStorageValue/LoadStorageValue

### ISSUE THREAD

**Issue by hawkerm** [ChrisDill/Raylib-cs-Examples#21]
1. Run StorageValues sample
2. Hit 'Enter' or 'Space' and see crash

Looks like both `SaveStorageValue` and `LoadStorageValue` both don't exist in native dll?

**Comment by ChrisDill** [comment]
Good catch! The example has been updated to match the changes in raylib.
