### ISSUE TITLE
Unsupported .FLAC in `MusicStreamDemo` ?

### ISSUE THREAD

**Issue by horseyhorsey** [ChrisDill/Raylib-cs-Examples#28]
Other formats are supported in the Raduio module, do you know how to get these working? Compile libs with different `raudio.c`?

**Comment by 9ParsonsB** [comment]
We only distribute the official raylib binaries. If you need extra features, you will need to compile it yourself.

Looking at raylib, they have FLAC disabled by default, not clear why:

default config:
https://github.com/raysan5/raylib/blob/5e1a81555ca130e2c6544add0e2391a8763e7e2a/src/config.h#L218

raudio #defines:
https://github.com/raysan5/raylib/blob/5e1a81555ca130e2c6544add0e2391a8763e7e2a/src/raudio.c#L25

**Comment by horseyhorsey** [comment]
I see, that seems easy enough. Thanks for pointing that out.

**Comment by horseyhorsey** [comment]
Only way I could manage to get to compile with the flags is to use the windows installer for Raylib which comes bundled with tooling and NP++. Recompile source after and using the provided `target.flac` file in `resources`

![image](https://github.com/ChrisDill/Raylib-cs-Examples/assets/5377332/86d8adda-ddd2-40de-8be1-8d86f17c8f48)
