### ISSUE TITLE
Physac example

### ISSUE THREAD

**Issue by RafaelOliveira** [ChrisDill/Raylib-cs-Examples#7]
Hi, I'm trying to use Physac-cs, but I don't have experience with the use of IntPtr (that is returned from CreatePhysicsBodyRectangle). Could be added a example, like the physics_demo.c that is in the Physac repo?

**Comment by ChrisDill** [comment]
Physac is experimental. There were some examples but I removed them as they didn't work correctly.
I am still deciding what to do with the experimental modules for Raylib-cs so I would not rely on them.
