### ISSUE TITLE
Lighting in shaders_basic_lighting doesn't work

### ISSUE THREAD

**Issue by HoutarouOreki** [ChrisDill/Raylib-cs-Examples#9]
![image](https://user-images.githubusercontent.com/16261733/126876470-2c13cb70-bfd1-417b-8b1e-bdd95cdd8f7d.png)

It worked with 3.5 before updating the repository to latest version.

**Comment by ChrisDill** [comment]
Thanks. I fixed the issue in Raylib-cs recently so the fix will be in the next release.

**Comment by ChrisDill** [comment]
@HoutarouOreki The fix is now available in the [3.7.0.1](https://github.com/ChrisDill/Raylib-cs/releases/tag/3.7.0.1) release and the examples are now using it. The example now works as expected!
